# Generated by Django 5.0.4 on 2024-05-13 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='points',
            new_name='total_museum_points',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_points', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('exhibits', models.ManyToManyField(related_name='rooms', to='api.exhibit')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoomPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='room_points',
            field=models.ManyToManyField(through='api.UserRoomPoints', to='api.room'),
        ),
    ]
