# Generated by Django 5.0.4 on 2024-05-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_points_user_total_museum_points_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='exhibits',
        ),
        migrations.RemoveField(
            model_name='room',
            name='points',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='room',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='api.room', to_field='room_number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exhibit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
